application_repository = "https://github.com/sree-1992/trainingdevops.cloud-repository.git"
project_name           = "trainingdevops"
project_env            = "production"
ami                    = "ami-013168dc3850ef002"
instance_type          = "t2.micro"
